config/routes.rb
Rails.application.routes.draw do
  namespace :site do
    get  'welcome/index'
    get  'search', to: 'search#questions'
    get  'subject/:subject_id/:subject', to: 'search#subject', as: 'search_subject'
    post 'answer', to: 'answer#question'
  end
  namespace :users_backoffice do
    get 'welcome/index'
    get 'profile', to: 'profile#edit'
    patch 'profile', to: 'profile#update'
    get 'zip_code', to: 'zip_code#show'
  end
  namespace :admins_backoffice do
    get 'welcome/index' # Dashboard
    resources :admins   # Administradores
    resources :subjects # Assuntos/Áreas
    resources :questions # Perguntas
  end
  
  devise_for :admins, skip:  [:registrations]
  devise_for :users
 
  get 'inicio', to: 'site/welcome#index'
  get 'backoffice', to: 'admins_backoffice/welcome#index'

  root to: 'site/welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :subject, counter_cache: true, inverse_of: :questions
  has_many :answers
  accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true
  # Kainari
  paginates_per 5 

  #Scopes  

  #CALLBACK
  after_create :set_statistic

  scope :_search_subject_, -> (page, subject_id){ includes(:answers, :subject).where(subject_id: subject_id).page(page)}

  scope :_search_, -> (page, term){ includes(:answers, :subjectrails).where("lower(description) LIKE ?", "%#{term.downcase}%").page(page)}
  
  scope :last_questions, -> (page) {includes(:answers).order("created_at desc").page(page)}


  private
  def set_statistic
    AdminStatistic.set_event(AdminStatistic::EVENTS[:total_questions])
  end

end

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
  before_action :verify_password, only: [:update]
  before_action :set_admin, only: [:edit, :update, :destroy]

  def index
    # Abir um console dentro da aplicação
    console
    @admins = Admin.all.page(params[:page])
    
  end

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to admins_backoffice_admins_path, notice: "Admin criado com sucesso!"
    else
      render :enew
      @admin.errors
    end
  end

  def edit
  end

  def update
    if @admin.update(params_admin)
      AdminMailer.update_email(current_admin, @admin).deliver_now
      redirect_to admins_backoffice_admins_path, notice: "Admin atualizado com sucesso!"
    else
      render :edit
      @admin.errors
    end
  end

  def destroy
    if @admin.destroy
      redirect_to admins_backoffice_admins_path, notice: "Admin excluído com sucesso!"
    else
      render :index
    end
  end

  private

  def verify_password
    if params[:admin][:password].blank? && params[:admin][:password].blank?
      params[:admin].extract!(:password, :password_confirmation)
    end
  end

  def set_admin
    @admin = Admin.find(params[:id])
  end

  def params_admin
    params.require(:admin).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/admins_backoffice/questions_controller.rb
class AdminsBackoffice::QuestionsController < AdminsBackofficeController
  before_action :set_question, only: [:edit, :update, :destroy]
  before_action :get_suibjects, only: [:new, :edit]

  def index
    @questions = Question.includes(:subject).order(:description).page(params[:page])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(params_question)
    if @question.save
      redirect_to admins_backoffice_questions_path, notice: "Questão cadastrada com sucesso!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @question.update(params_question)
      redirect_to admins_backoffice_questions_path, notice: "Questão atualizada com sucesso!"
    else
      render :edit
    end
  end

  def destroy
    if @question.destroy
      redirect_to admins_backoffice_question_path, notice: "Questão excluída com sucesso!"
    else
      render :index
    end
  end

  private

  def params_question
    params.require(:question).permit(:description, :subject_id,
      answers_attributes: [:id, :description, :correct, :_destroy])
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def get_suibjects
    @subjects = Subject.all
  end
end

app/controllers/admins_backoffice/subjects_controller.rb
class AdminsBackoffice::SubjectsController < AdminsBackofficeController
  before_action :set_subject, only: [:edit, :update, :destroy]

  def index
    @subjects = Subject.all.order(:description).page(params[:page])
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(params_subject)
    if @subject.save
      redirect_to admins_backoffice_subjects_path, notice: "Assunto criado com sucesso!"
    else
      render :enew
      @subject.errors
    end
  end

  def edit
  end

  def update
    if @subject.update(params_subject)
      redirect_to admins_backoffice_subjects_path, notice: "Assuntos atualizado com sucesso!"
    else
      render :edit
      @subject.errors
    end
  end

  def destroy
    if @subject.destroy
      redirect_to admins_backoffice_subjects_path, notice: "Assunto excluído com sucesso!"
    else
      render :index
    end
  end

  private

  def set_subject
    @subject = Subject.find(params[:id])
  end

  def params_subject
    params.require(:subject).permit(:description)
  end
end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  def index
    @total_questions = AdminStatistic.total_questions
    @total_users = AdminStatistic.total_users
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
    before_action :authenticate_admin!
    layout 'admins_backoffice'
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/questions_helper.rb
module AdminsBackoffice::QuestionsHelper
end

app/helpers/admins_backoffice/subjects_helper.rb
module AdminsBackoffice::SubjectsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
  def translate_attribute(object = nil, method = nil)
    if object && method
      object.model.human_attribute_name(method)
    else
      "informe os atributos corremante"
    end
  end
end

app/views/admins_backoffice/questions/_answer_fields.html.erb
<div class="nested-fields">
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.check_box :correct %> Correta?
  
  <%= link_to_remove_association("Remover", f) %>

</div>

app/views/admins_backoffice/questions/edit.html.erb
<%= render partial: 'admins_backoffice/questions/shared/form',
locals: {action_message: 'Editando'} %>

app/views/admins_backoffice/questions/index.html.erb
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800"><%= t('messages.listing', model: @questions.model_name.human(count:2))%></h1>
</div>
<hr>
<div class="row">
  <div class="col-sm-12">
    <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
      <thead>
        <tr role="row">
          <th class="sorting sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 0.5rem;"><%= translate_attribute(@questions, :id)%></th>
          <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 2rem;"><%= translate_attribute(@questions, :subject) %></th>
          <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 20rem;"><%= translate_attribute(@questions, :description) %></th>
          <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 1rem;"><%= link_to new_admins_backoffice_question_path, class:"btn btn-success btn-circle btn-sm" do %>
              <i class="fa fa-plus"></i>
            <% end %></th>
        </thead>
        <tfoot>
          <tr>
            <th rowspan="1" colspan="1"><%=translate_attribute(@questions, :id)%></th>
            <th rowspan="1" colspan="1"><%=translate_attribute(@questions, :subject)%></th>
            <th rowspan="1" colspan="1"><%=translate_attribute(@questions, :description)%></th>
            <th rowspan="1" colspan="1"><%= link_to new_admins_backoffice_question_path, class:"btn btn-success btn-circle btn-sm" do %>
                <i class="fa fa-plus"></i>
              <% end %>
            </th>
          </tfoot>
          <tbody>
            <% @questions.each do |question|%>
              <tr class="odd">
                <td class="sorting_1"><%= question.id %></td>
                <td><%= question.subject.description.truncate(30) %></td>
                <td><%= question.description.truncate(90) %></td>
                <td style="width: 10%">
                  <%= link_to edit_admins_backoffice_question_path(question), class:"btn btn-primary btn-circle btn-sm" do %>
                    <i class="fa fa-edit"></i>
                  <% end %>
                  <%= link_to admins_backoffice_question_path(question), method: :delete, class:"btn btn-danger btn-circle btn-sm", data: {confirm: t('messages.confirm_with', item: question.description.truncate(15))} do %>
                    <i class="fas fa-trash"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      
      </div>
    </div>

app/views/admins_backoffice/questions/new.html.erb
<%= render partial: 'admins_backoffice/questions/shared/form',
locals: {action_message: 'Novo'} %>